#include <algorithm>
#include <chrono>
#include <iostream>
#include <limits>
#include <sstream>
#include <string>
#include <thread>
#ifndef FUNCTIONS_H
#define FUNCTIONS_H
void add_item();
void add_items();
void remove_item();
void remove_items();
void manage_items();
void manage_categories();
void view_tables();
void display_statistics();
void exit_main_menu();
#endif //FUNCTIONS_H
